#修改TNAME: K2P-5.0 中的K2P-5.0为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: SSH

on:
  workflow_dispatch:
    inputs:
      name:
        description: "SSH connection"
        required: true
        default: "GO"
  # release:
  #   types: [published]
  push:
    tags:
      - "v*"
  #  branches:
  #    - master
  #  schedule:
  #    - cron: 0 8 * * 5
  #watch:
  #  types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
          token: ${{ secrets.R_TOKEN }}
        run: |
          sudo apt-get update
          sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot kmod \
          cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
          pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
      - name: Clone source code
        run: |
          git clone -b chongshengB --depth=1 https://github.com/Yh793/rt-n56u.git /opt/rt-n56u
      - name: Clone source code adg
        run: |
          git clone --branch "v0.104.0" --depth=1 "https://github.com/AdguardTeam/AdGuardHome" /opt/adguard
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: set go
        run: |
          cd /opt/hostedtoolcache/go
          #rm -rf /opt/hostedtoolcache/go/1.14.10
          #mv 1.15.3 1.14.10

      - name: Update UPX
        run: |
          mkdir -p /opt/upx
          cd /opt/upx
          wget https://github.com/upx/upx/releases/download/v3.93/upx-3.93-amd64_linux.tar.xz
          tar -Jxf upx*.tar.xz
          sudo cp upx*/upx /usr/bin

      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0

      - name: Remove obsolete firmwares on artifacts
        uses: c-hive/gha-remove-artifacts@v1.2.0
        if: always()
        with:
          age: '3 day'